### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by tz1** [chiengineer/Eagle-Libraries#1]
I think the various bits are covered under different licenses - the original cadsoft - are these included?  SparkFun last I checked had an "non-commercial use".  Others are public and freely redistributable.

So under what terms can I use the version that gets checked out from here?

**Comment by chiengineer** [comment]
For now the repository is a collection from external sources. I'm tryig to figure out a good way to detail the status of individual licences (text file?) but for now, the best I can say is whatever is designated in the library file description.  Having gone through them all though the general gist is that most have no licencse while others just name authors.

To be honest, there's not much that CAN be licensed because most of that information is available from the vendor themselves.  But I'm not a lawyer.
